linters:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - contextcheck 
  - depguard
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - misspell
  - nilerr
  - testpackage
  - wastedassign
  - whitespace
  - wrapcheck
  - wsl
  - zerologlint